# Generated by Django 2.2.5 on 2021-07-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lecturers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Age', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('faculty', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Age', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=200)),
                ('faculty', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='lecturers',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
